### ISSUE TITLE
[Bug] No Speech Option

### ISSUE THREAD

**Issue by zero77** [ONLYOFFICE/plugin-speech#8]
When i follow the instructions in the reed me there is no speech option.

My environment:
Debian sid
onlyoffice-desktopeditors  5.6.4 (snap edge)

![image](https://user-images.githubusercontent.com/16563034/94340176-9630b180-fff7-11ea-9558-8f709d661c78.png)

![image](https://user-images.githubusercontent.com/16563034/94340223-f58ec180-fff7-11ea-9ae7-2dc9ad755ef6.png)

**Comment by ShockwaveNN** [comment]
I think it's same problem as in https://github.com/ONLYOFFICE/plugin-speech/issues/52#issuecomment-1049863549

Relate to a limit of free access to [ResponsiveVoice service](https://responsivevoice.org/)

I'll make bug as main one about this, because seems we forgot about this issue, sorry
